Ruby/RailsI/ContViews/dojo_dashboard/config/routes.rb
Rails.application.routes.draw do
    root "dojos#index"
    resources :dojos do
        resources :students
    end
    # get "dojos/new" => "dojos#new"
    # post "dojos" => "dojos#create"
    # get "dojos/:id" => "dojos#show"
    # get "dojos/:id/edit" => "dojos#edit"
    # patch "dojos/:id" => "dojos#update"
    # delete "dojos/:id" => "dojos#destroy"
end

Ruby/RailsI/ContViews/dojo_dashboard/app/models/dojo.rb
class Dojo < ActiveRecord::Base
    has_many :students, dependent: :destroy

    validates :branch, :street, :city, :state, presence: true
    validates :state, length: { is: 2 }
end

Ruby/RailsI/ContViews/dojo_dashboard/app/models/student.rb
class Student < ActiveRecord::Base
    belongs_to :dojo

    EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
    validates :first_name, :last_name, presence: true
    validates :email, presence:true, uniqueness: { case_sensitive: false}, format: { with: EMAIL_REGEX }

    def self.with_dojo student_id
        self.joins(:dojo).where("students.id = ?", student_id).select(:id, :first_name, :last_name, :email, :branch, :dojo_id, :created_at).first
    end

    def self.cohort student
        self.where("id != ? AND dojo_id = ? AND DATE(created_at) = ?", student.id, student.dojo_id, student.created_at.strftime("%Y-%m-%d"))
    end
end

Ruby/RailsI/ContViews/dojo_dashboard/app/controllers/dojos_controller.rb
class DojosController < ApplicationController
    def index
        @dojos = Dojo.all
    end

    def new
        @dojo = Dojo.new
    end

    def create
        @dojo = Dojo.new(dojo_params)
        if @dojo.save
            redirect_to root_url, notice: "You have successfully created a Dojo!"
        else
            flash[:errors] = @dojo.errors.full_messages
            redirect_to :back
        end
    end

    def show
        @dojo = Dojo.find(params[:id])
    end

    def edit
        @dojo = Dojo.find(params[:id])
    end

    def update
        @dojo = Dojo.find(params[:id])
        if @dojo.update(dojo_params)
            redirect_to root_path, notice: "You have successfully updated a Dojo!"
        else
            flash[:errors] = @dojo.errors.full_messages
            redirect_to :back
        end
    end

    def destroy
        Dojo.find(params[:id]).destroy
        redirect_to :root
    end

    private
        def dojo_params
            params.require(:dojo).permit(:branch, :street, :city, :state)
        end
end

Ruby/RailsI/ContViews/dojo_dashboard/app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def new
        @dojos = Dojo.all
        @dojo = Dojo.find(params[:dojo_id])
    end

    def create
        @student = Student.new(student_params)

        if @student.save
            redirect_to "dojos/#{@student.dojo_id}", notice: "You have successfully created a Student!"
        else
            flash[:errors] =@student.errors.full_messages
            redirect_to :back
        end
    end

    def show
        @student = Student.with_dojo(params[:id])

        @cohort = Student.cohort(@student)
    end

    def edit
        @dojos = Dojo.all
        @student = Student.cohort(@student)
    end

    def update
        @student = Student.find(params[:id])

        if @student.update(student_params)
            redirect_to dojo_student_path(@student.dojo_id, @student.id), notice: "You have successfully updated a Student!"
        else
            flash[:errors] = @student.errors.full_messages
            redirect_to :back
        end
    end

    def destroy
        Student.find(params[:id])
        redirect_to :root
    end

    private
        def student_params
            params.require(:student).permit(:first_name, :last_name, :email, :dojo_id)
        end
end

Ruby/RailsI/ContViews/dojo_dashboard/app/helpers/dojos_helper.rb
module DojosHelper
end

Ruby/RailsI/ContViews/dojo_dashboard/app/helpers/students_helper.rb
module StudentsHelper
end

Ruby/RailsI/ContViews/dojo_dashboard/app/views/dojos/edit.html.erb
<h1>Edit <%= @dojo.branch %></h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |e| %>
        <p><%= e %></p>
    <% end %>
<% end %>

<form  action="/dojos/<%= @dojo.id %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <p>
        <label>Branch:</label>
        <input type="text" name="dojo[branch]" value="<%= @dojo.branch %>">
    </p>
    <p>
        <label>Street:</label>
        <input type="text" name="dojo[street]" value="<%= @dojo.street %>">
    </p>
    <p>
        <label>City:</label>
        <input type="text" name="dojo[city]" value="<%= @dojo.city %>">
    </p>
    <p>
        <label>State:</label>
        <input type="text" name="dojo[state]" value="<%= @dojo.state %>">
    </p>
    <input type="submit" value="Update Dojo">
</form>

<%= link_to "Back", root_path %>

Ruby/RailsI/ContViews/dojo_dashboard/app/views/dojos/index.html.erb
<h1>Listing <%= pluralize(@dojos.count, "Dojo") %></h1>

<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>

<table>
    <thead>
        <tr>
            <td>Coding Dojo Branch</td>
            <td>Street</td>
            <td>City</td>
            <td>State</td>
        </tr>
    </thead>
    <tbody>
        <% @dojos.each do |dojo| %>
        <tr>
            <td><%= dojo.branch %></td>
            <td><%= dojo.street %></td>
            <td><%= dojo.city %></td>
            <td><%= dojo.state %></td>
            <td>
                <%= link_to "Show", dojo %> |
                <%= link_to "Edit", edit_dojo_path(dojo) %> |
                <%= link_to "Delete", dojo, data: { method: :delete, confirm: "Are you sure?" } %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= link_to "New Dojo", new_dojo_path %>

Ruby/RailsI/ContViews/dojo_dashboard/app/views/dojos/new.html.erb
<h1>New Dojo</h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |e| %>
        <p><%= e %></p>
    <% end %>
<% end %>

<form action="/dojos" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <p>
        <label>Branch:</label>
        <input type="text" name="dojo[branch]">
    </p>
    <p>
        <label>Street:</label>
        <input type="text" name="dojo[street]">
    </p>
    <p>
        <label>City:</label>
        <input type="text" name="dojo[city]">
    </p>
    <p>
        <label>State:</label>
        <input type="text" name="dojo[state]">
    </p>
    <input type="submit" value="Create">
</form>

<%= link_to "Back", root_path %>

Ruby/RailsI/ContViews/dojo_dashboard/app/views/dojos/show.html.erb
<h1><%= @dojo.branch %></h1>

<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>

<p>Address: <%= @dojo.street %></p>
<p>City: <%= @dojo.city %> State: <%= @dojo.state %></p>

<h2>Student Roster</h2>

<table>
    <thead>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Actions</th>
    </thead>
    <tbody>
        <% if @students %>
            <% @students.each do |s|%>
                <tr>
                    <td><%= s.first_name %></td>
                </tr>
            <% end %>
        <% end %>
    </tbody>
</table>

<%= link_to "Home", root_path %> | <%= link_to "Edit", edit_dojo_path(@dojo) %> | <%= link_to "Add Student", new_dojo_student_path(@dojo) %>

Ruby/RailsI/ContViews/dojo_dashboard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DojoDashboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>